# Generated by Django 3.0.5 on 2020-12-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='history',
            new_name='daysleft',
        ),
        migrations.AddField(
            model_name='task',
            name='extended',
            field=models.IntegerField(default=0),
        ),
    ]
